### ISSUE TITLE
we need an installer MSI

### ISSUE THREAD

**Issue by ksobon** [HOKGroup/Zombie#28]
we need one because it will obviously make deployment easier. Also things to keep in mind when putting together an installer...

- allow for specifying a location to where Zombie will be installed
- Zombie has two parts to it, the service and gui. installer should allow to install one or the other. for some deployment scenarios you don't want to give the gui to users. its really useful for admins only. 
- when deploying at a large company, it would be good to allow for a silent install with command arguments that would automatically set ImagePath for the service autostartup path. that's a place that settings file path and token get put into.

**Comment by ksobon** [comment]
http://davton.com/blog/how-to-pass-custom-actions-to-a-wix-installer-using-command-line-arguments/

**Comment by radumg** [comment]
just a thought to consider/debate, but tokens should/could be placed in registry/environment variables instead of a network location/disk - registry access is usually disabled for users in organisations and it'd be an easy way for IT admins to roll these out from AD via a GPO or similar. Also seems safer than a place on disk that may or may not be visible/accesible to end users ?
